export const mockDrifts = [
  {
    id: "drift-001",
    date: "2024-01-15T10:30:00",
    type: "negative",
    title: "Database layer dependency spike",
    summary: "Tight coupling introduced between user service and reporting database.",
    functionality: "User profile reporting and analytics.",
    advantage: null,
    disadvantage: "Increased risk of cascading failures and harder schema evolution.",
    root_cause: "Short-term deadline led to bypassing API layer.",
    files_changed: ["services/user/db.py", "reports/queries/user_analytics.sql"],
    commit_hash: "abc12345",
    repo_url: "https://github.com/example/archdrift-demo",
    teams: ["Backend", "DB"],
    driftType: "architecture",
    impactLevel: "high",
    riskAreas: ["Maintainability", "Testability"],
    recommendedActions: [
      "Extract database access into a dedicated service layer function.",
      "Update architecture guidelines/ADR to reinforce 'API → Service → DB' rule.",
      "Add regression tests to cover API behaviour via the service layer.",
    ],
  },
  {
    id: "drift-002",
    date: "2024-03-02T09:15:00",
    type: "positive",
    title: "Introduced API gateway for external traffic",
    summary: "Centralized ingress with routing, auth and rate limiting.",
    functionality: "External client access to core services.",
    advantage: "Better control, security and observability at the edge.",
    disadvantage: null,
    root_cause: "Growing number of external clients and ad-hoc service exposure.",
    files_changed: ["infra/api-gateway.yaml", "services/auth/config.yml"],
    commit_hash: "def67890",
    repo_url: "https://github.com/example/archdrift-demo",
    teams: ["Infrastructure", "Backend"],
    driftType: "config_env",
    impactLevel: "medium",
    riskAreas: ["Maintainability"],
    recommendedActions: [
      "Ensure new routes use the service layer instead of accessing DB directly.",
      "Document the new abstraction in architecture docs/ADR.",
    ],
  },
  {
    id: "drift-003",
    date: "2024-04-10T14:20:00",
    type: "negative",
    title: "Circular dependency between payment and order modules",
    summary: "Payment service now imports order models directly, creating a circular reference.",
    functionality: "Payment processing and order status updates.",
    advantage: null,
    disadvantage: "Makes code harder to test and can cause import errors in certain scenarios.",
    root_cause: "Quick fix to avoid refactoring shared models.",
    files_changed: ["services/payment/processor.py", "models/order.py", "services/order/status.py"],
    commit_hash: "ghi34567",
    repo_url: "https://github.com/example/archdrift-demo",
    teams: ["Backend", "DB"],
    driftType: "architecture",
    impactLevel: "high",
    riskAreas: ["Maintainability", "Complexity"],
    recommendedActions: [
      "Refactor modules to remove circular imports (introduce a shared lower-level module if needed).",
      "Add an architecture rule to prevent circular dependencies in future.",
    ],
  },
  {
    id: "drift-004",
    date: "2024-05-22T11:45:00",
    type: "positive",
    title: "Refactored to use dependency injection pattern",
    summary: "Services now use dependency injection, making components more testable and loosely coupled.",
    functionality: "Service layer architecture improvements.",
    advantage: "Improved testability, flexibility, and adherence to SOLID principles.",
    disadvantage: null,
    root_cause: "Refactoring effort to improve code quality and test coverage.",
    files_changed: ["services/base_service.py", "services/user_service.py", "api/routes.py", "config/dependencies.py"],
    commit_hash: "jkl89012",
    repo_url: "https://github.com/example/archdrift-demo",
    teams: ["Backend"],
    driftType: "architecture",
    impactLevel: "medium",
    riskAreas: ["Testability"],
    recommendedActions: [
      "Adopt DI for new services and routes to keep dependencies explicit.",
      "Add unit tests that inject test doubles for key collaborators.",
    ],
  },
  {
    id: "drift-005",
    date: "2024-06-18T16:30:00",
    type: "negative",
    title: "Business logic leaked into API route handlers",
    summary: "Complex validation and transformation logic moved directly into route handlers.",
    functionality: "User registration and profile updates.",
    advantage: null,
    disadvantage: "Violates separation of concerns, makes routes harder to test and maintain.",
    root_cause: "Time pressure led to skipping service layer abstraction.",
    files_changed: ["api/users.py", "api/auth.py"],
    commit_hash: "mno45678",
    repo_url: "https://github.com/example/archdrift-demo",
    teams: ["Backend"],
    driftType: "architecture",
    impactLevel: "high",
    riskAreas: ["Maintainability", "Testability"],
    recommendedActions: [
      "Extract business logic from route handlers into dedicated service functions.",
      "Add integration tests that verify route behavior through the service layer.",
      "Update code review checklist to catch similar violations early.",
    ],
  },
];

